const catalogData: { category: string; image: string; name: string; price: string; sold: number }[] = [
    {
        category: 'Sayur',
        image: '/images/bayam.png',
        name: 'Bayam',
        price: 'Rp2.500',
        sold: 5,
    },
    {
        category: 'Sayur',
        image: '/images/jagung.png',
        name: 'Jagung',
        price: 'Rp5.000',
        sold: 5,
    },
    {
        category: 'Sayur',
        image: '/images/tomat.jpg',
        name: 'Tomat',
        price: 'Rp5.000',
        sold: 5,
    },
    {
        category: 'Sayur',
        image: '/images/kangkung.jpg',
        name: 'Kangkung',
        price: 'Rp2.500',
        sold: 5,
    },
    {
        category: 'Sayur',
        image: '/images/sawi-putih.jpg',
        name: 'Sawi Putih',
        price: 'Rp3.000',
        sold: 5,
    },
    {
        category: 'Sayur',
        image: '/images/pakcoy.jpg',
        name: 'Pakcoy',
        price: 'Rp3.000',
        sold: 5,
    },
    {
        category: 'Sayur',
        image: '/images/timun.jpg',
        name: 'Mentimun',
        price: 'Rp3.000',
        sold: 5,
    },
    {
        category: 'Sayur',
        image: '/images/brokoli.jpg',
        name: 'Brokoli',
        price: 'Rp5.000',
        sold: 5,
    },
    {
        category: 'Sayur',
        image: '/images/oyong.jpg',
        name: 'Sayur Oyong',
        price: 'Rp4.000',
        sold: 5,
    },
    {
        category: 'Buah',
        image: '/images/shine-muscat.jpg',
        name: 'Anggur Shine Muscat',
        price: 'Rp43.000',
        sold: 5,
    },
    {
        category: 'Buah',
        image: '/images/pisang.jpg',
        name: 'Pisang',
        price: 'Rp10.000',
        sold: 5,
    },
    {
        category: 'Daging',
        image: '/images/ayam.jpg',
        name: 'Ayam Broiler',
        price: 'Rp34.000',
        sold: 5,
    },
    {
        category: 'Makanan Ringan',
        image: '/images/kusuka.jpg',
        name: 'Kusuka Original',
        price: 'Rp7.000',
        sold: 5,
    },
    {
        category: 'Minuman',
        image: '/images/fruit-tea.jpg',
        name: 'Fruit Tea Anggur',
        price: 'Rp7.000',
        sold: 5,
    },
    {
        category: 'Roti & Kue',
        image: '/images/sari-roti.jpg',
        name: 'Sari Roti Kupas',
        price: 'Rp16.000',
        sold: 5,
    },
    {
        category: 'Susu & Olahan',
        image: '/images/keju.jpg',
        name: 'Keju Cheddar',
        price: 'Rp25.000',
        sold: 5,
    },
    ];

export { catalogData };